team_manager/config/routes.rb
TeamManager::Application.routes.draw do
  root "dashbords#home"
  
  devise_for :users
  resources :projects do
    resources :reports
	resources :tasks
  end
  resources :users
  resources :materials
  resources :accountings do
    resources :images
  end
  resources :accountings
  
  get "static_pages/contact"
  get "static_pages/usage"
  
  get "projects/:id/members_edit", to:"projects#members_edit", as: "project_members_edit"
  post "projects/:id/members_edit", to:"projects#members_edit"
  delete "projects/:id/members_edit/:user_id", to:"projects#member_delete"
  
  get "materials/:id/users_edit", to:"materials#users_edit", as: "material_users_edit"
  post "materials/:id/users_edit", to:"materials#users_edit"
  delete "materials/:id/users_edit/:user_id", to:"materials#user_delete"
  
  get "projects/:project_id/reports/:id//users_edit", to:"reports#users_edit", as: "report_users_edit"
  post "projects/:project_id/reports/:id/users_edit", to:"reports#users_edit"
  delete "projects/:project_id/reports/:id/users_edit/:user_id", to:"reports#user_delete"
  
  get "projects/:project_id/tasks/:id//users_edit", to:"tasks#users_edit", as: "task_users_edit"
  post "projects/:project_id/tasks/:id/users_edit", to:"tasks#users_edit"
  delete "projects/:project_id/tasks/:id/users_edit/:user_id", to:"tasks#user_delete"
  
  get 'accountings/:id/edit_status' => 'accountings#edit_status', as: :edit_status

end

team_manager/app/models/accounting.rb
class Accounting < ActiveRecord::Base
  belongs_to :user
  has_many :images, as: :imageable, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :images
  
  validates :title, presence: true
  validates :purpose, presence: true
  validates :application_date, presence: true  
  validates :status, presence:true
end

team_manager/app/models/event.rb
class Event < ActiveRecord::Base
end

team_manager/app/models/event2.rb
class Event2 < ActiveRecord::Base
end

team_manager/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :image_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image_file, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/models/material.rb
class Material < ActiveRecord::Base
	has_many :materials_users, dependent: :destroy
    has_many :users, through: :materials_users
	accepts_nested_attributes_for :materials_users

    validates :title, presence:true
	validates :filename, presence:true
	validates :filetype, presence:true
end

team_manager/app/models/material_user.rb
class MaterialUser < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

team_manager/app/models/materials_user.rb
class MaterialsUser < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

team_manager/app/models/project.rb
class Project < ActiveRecord::Base
    has_many :reports, dependent: :destroy
	has_many :tasks, dependent: :destroy

	has_many :projects_users, dependent: :destroy
	has_many :users, through: :projects_users
	accepts_nested_attributes_for :projects_users

    validates :title, presence: true
	validates :description, presence: true
	#validates :project_manager_id, presence: true

end

team_manager/app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

team_manager/app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :project
  
  has_many :reports_users
  has_many :users, through: :reports_users
  accepts_nested_attributes_for :reports_users

  validates :title, presence: true
  validates :text, presence: true
end

team_manager/app/models/report_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :report
  belongs_to :user
end

team_manager/app/models/reports_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :report
end

team_manager/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

team_manager/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  
  has_many :tasks_users
  has_many :users, through: :tasks_users
  accepts_nested_attributes_for :tasks_users

  validates :title, presence: true
  validates :due, presence: true
  validates :content, presence: true
end

team_manager/app/models/tasks_user.rb
class TasksUser < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

team_manager/app/models/user.rb
class User < ActiveRecord::Base
  has_many :materials_users
  has_many :materials, through: :materials_users

  has_many :tasks_users
  has_many :tasks, through: :tasks_users
  
  has_many :reports_users
  has_many :reports, through: :reports_users

  has_many :projects_users, dependent: :destroy
  has_many :projects, through: :projects_users

  has_many :accountings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :description, presence: true
  validates :generation, presence: true
  validates :name, presence: true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "60x60>" }, :default_url => "defaults/avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(10)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
	redirect_to projects_path
  end

  def show
    @user = User.find(params[:id])
	@materials = @user.materials.limit(3)
	@projects = @user.projects.limit(3)
	@reports = @user.reports.limit(3)
	@tasks = @user.tasks.limit(3)
	@accountings = @user.accountings.limit(3)
  end

  private
    def user_params
	  params.require(:user).permit(:id, :name, :email, 
	    materials_users_attributes: [:id, :material_id, :user_id],
	    materials_attributes: [:id, :title, :description],
	    reports_attributes: [:id, :title],
	    reports_users_attributes: [:id, :report_id, :user_id], 
	    projects_attributes: [:id, :title, :description],
	    projects_users_attributes: [:id, :project_id, :user_id],
	    tasks_attributes: [:id, :title, :due, :content],
	    tasks_users_attributes: [:id, :task_id, :user_id]
	  )
    end
end

team_manager/app/helpers/events_helper.rb
module EventsHelper
end

team_manager/app/helpers/images_helper.rb
module ImagesHelper
end

team_manager/app/helpers/reports_helper.rb
module ReportsHelper
end

team_manager/app/helpers/tasks_helper.rb
module TasksHelper
end

team_manager/app/helpers/usages_helper.rb
module UsagesHelper
end

team_manager/app/helpers/users_helper.rb
module UsersHelper
end

team_manager/app/views/users/index.html.erb
<h1>メンバー一覧</h1>
<%= paginate @users %>
<table class="table table-default">
  <tr>
    <th></th>
    <th>名前</th>
    <th>代</th>
    <th>一言コメント</th>
    <th>email</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
	  <td><%= image_tag user.avatar.url(:thumb) %></td>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= user.generation %></td>
      <td><%= user.description %></td>   
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

team_manager/app/views/users/show.html.erb
<div class="col-md-4">
  <div class="well">
    <h3><%= @user.name %></h3>
    <%= image_tag @user.avatar.url %>
    <br>
    <table class="table">
      <tr>
        <td>代</td>
        <td><%= @user.generation%></td>
      </tr>
      <tr>
        <td>一言コメント</td>
     　 <td><%= @user.description%></td>
      </tr>
      <tr>
        <td>連絡先</td>
        <td><%= @user.email %></td>
      </tr>
    </table>
    <% if current_user == @user %>
      <%=  link_to "プロフィールを編集する", edit_user_registration_path %>
    <% end %>
  </div>
</div>

<div class="col-md-8">
  <h4>【資料】</h4>
  <table class="table">
    <tr>
      <td>ファイル名</td>
      <td>概要</td>
    </tr>
    <% @materials.each do |m|%>
      <tr>
        <td><%= link_to m.title, material_path(m) %></td>
        <td><%= m.text %></td>
      </tr>
    <% end %>
  </table>

  <h4>【プロジェクト】</h4>
  <table class="table">
    <tr>
      <td>プロジェクト名</td>
      <td>概要</td>
    </tr>
    <% @projects.each do |p|%>
      <tr>
        <td><%= link_to p.title, project_path(p) %></td>
        <td><%= p.description %></td>
      </tr>
    <% end %>
  </table>
  
  <h4>【資料】</h4>
  <table class="table">
  <tr>
    <td>ファイル名</td>
    <td>関連ユーザー</td>
  </tr>
  <% @materials.each do |m| %>
  <tr>
      <td><%= link_to m.title, material_path(m) %></td>
	  <td>
	    <% m.users.each do |mu| %>
	      <%= mu.name %>, 
	    <% end %>
      </td>
  </tr>
  <% end %>
</table>

  <h4>【レポート】</h4>
  <table class="table">
    <tr>
      <td>タイトル</td>
      <td>プロジェクト名</td>
      <td>内容</td>
    </tr>
    <% @reports.each do |r|%>
      <tr>
        <td><%= link_to r.title, project_report_path(r.project_id, r) %></td>
        <td><%= r.project.title %></td>
        <td><%= r.text %></td>
      </tr>
    <% end %>
  </table>

  <h4>【タスク】</h4>
  <table class="table">
    <tr>
      <td>タイトル</td>
      <td>プロジェクト名</td>
      <td>締め切り</td>
    </tr>
    <% @tasks.each do |t|%>
    <tr>
        <td><%= link_to t.title, project_task_path(t.project_id, t) %></td>
        <td><%= t.project.title %></td>
        <td><%= t.due.to_s(:db)%></td>
    </tr>
    <% end %>
  </table>


  <h4>【経理申請】</h4>
  <table class="table">
    <tr>
      <td>タイトル</td>
      <td>申請日</td>
      <td>申請状況</td>
    </tr>
    <% @accountings.each do |a|%>
    <tr>
        <td><%= link_to a.title, accounting_path(a) %></td>
        <td><%= a.application_date %></td>
        <td>
          <% case a.status %>
          <% when 1 %>
            申請中
          <% when 2 %>
            承認
          <% when 3 %>
            却下
          <% end %>
        </td>
    </tr>
  <% end %>
  </table>