team_manager/config/routes.rb
TeamManager::Application.routes.draw do
  root "dashbords#home"
  
  devise_for :users
  resources :projects do
    resources :reports
	resources :tasks
  end
  resources :users
  resources :materials
  resources :accountings do
    resources :images
  end
  resources :accountings
  
  get "static_pages/contact"
  get "static_pages/usage"
  
  get "projects/:id/members_edit", to:"projects#members_edit", as: "project_members_edit"
  post "projects/:id/members_edit", to:"projects#members_edit"
  delete "projects/:id/members_edit/:user_id", to:"projects#member_delete"
  
  get "materials/:id/users_edit", to:"materials#users_edit", as: "material_users_edit"
  post "materials/:id/users_edit", to:"materials#users_edit"
  delete "materials/:id/users_edit/:user_id", to:"materials#user_delete"
  
  get "projects/:project_id/reports/:id//users_edit", to:"reports#users_edit", as: "report_users_edit"
  post "projects/:project_id/reports/:id/users_edit", to:"reports#users_edit"
  delete "projects/:project_id/reports/:id/users_edit/:user_id", to:"reports#user_delete"
  
  get "projects/:project_id/tasks/:id//users_edit", to:"tasks#users_edit", as: "task_users_edit"
  post "projects/:project_id/tasks/:id/users_edit", to:"tasks#users_edit"
  delete "projects/:project_id/tasks/:id/users_edit/:user_id", to:"tasks#user_delete"
  
  get 'accountings/:id/edit_status' => 'accountings#edit_status', as: :edit_status

end

team_manager/app/models/accounting.rb
class Accounting < ActiveRecord::Base
  belongs_to :user
  has_many :images, as: :imageable, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :images
  
  validates :title, presence: true
  validates :purpose, presence: true
  validates :application_date, presence: true  
  validates :status, presence:true
end

team_manager/app/models/event.rb
class Event < ActiveRecord::Base
end

team_manager/app/models/event2.rb
class Event2 < ActiveRecord::Base
end

team_manager/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :image_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image_file, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/models/material.rb
class Material < ActiveRecord::Base
	has_many :materials_users, dependent: :destroy
    has_many :users, through: :materials_users
	accepts_nested_attributes_for :materials_users

    validates :title, presence:true
	validates :filename, presence:true
	validates :filetype, presence:true
end

team_manager/app/models/material_user.rb
class MaterialUser < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

team_manager/app/models/materials_user.rb
class MaterialsUser < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

team_manager/app/models/project.rb
class Project < ActiveRecord::Base
    has_many :reports, dependent: :destroy
	has_many :tasks, dependent: :destroy

	has_many :projects_users, dependent: :destroy
	has_many :users, through: :projects_users
	accepts_nested_attributes_for :projects_users

    validates :title, presence: true
	validates :description, presence: true
	#validates :project_manager_id, presence: true

end

team_manager/app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

team_manager/app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :project
  
  has_many :reports_users
  has_many :users, through: :reports_users
  accepts_nested_attributes_for :reports_users

  validates :title, presence: true
  validates :text, presence: true
end

team_manager/app/models/report_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :report
  belongs_to :user
end

team_manager/app/models/reports_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :report
end

team_manager/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

team_manager/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  
  has_many :tasks_users
  has_many :users, through: :tasks_users
  accepts_nested_attributes_for :tasks_users

  validates :title, presence: true
  validates :due, presence: true
  validates :content, presence: true
end

team_manager/app/models/tasks_user.rb
class TasksUser < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

team_manager/app/models/user.rb
class User < ActiveRecord::Base
  has_many :materials_users
  has_many :materials, through: :materials_users

  has_many :tasks_users
  has_many :tasks, through: :tasks_users
  
  has_many :reports_users
  has_many :reports, through: :reports_users

  has_many :projects_users, dependent: :destroy
  has_many :projects, through: :projects_users

  has_many :accountings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :description, presence: true
  validates :generation, presence: true
  validates :name, presence: true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "60x60>" }, :default_url => "defaults/avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project, only: [:new, :create, :show, :edit, :update, :destroy, :index, :users_edit, :user_delete]
  before_action :set_task, only: [:show, :edit, :update, :destroy, :users_edit, :user_delete]
  
  def new
	@task = @project.tasks.build
	@task.tasks_users.build
  end

  def create
    @task = @project.tasks.create(task_params)
	if @task.save
	  redirect_to project_task_path(@project, @task)
	else
	  render 'new'
	end
  end

  def index
	@tasks = @project.tasks.all
  end

  def show
    @task = @project.tasks.find(params[:id])
	@assignees = @task.users.all
  end
  
  def update
    @task = @project.tasks.find(params[:id])
	if @task.update(task_params)
	  redirect_to project_task_path(@project, @task)
	else
	  render 'edit'
	end
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def destroy
    @report = @project.tasks.find(params[:id])
    @report.destroy
    redirect_to project_path(@project)
  end
 
  def users_edit
    @new_user = @task.tasks_users.build
    render 'users_edit'
  end

  def user_delete
    @task_user = @task.tasks_users.where(user_id: params[:user_id], task_id: @task.id).first
    @task_user.destroy
    redirect_to task_users_edit_path(@task.project_id, @task)
  end


  private
    def task_params
      params.require(:task).permit(:id, :title, :project_id, :content, :due, users_attributes: [:id, :name], tasks_users_attributes: [:id, :task_id, :user_id])
    end
  
    def set_project
      @project = Project.find(params[:project_id])
    end
    
	def set_task
      @task = Task.find(params[:id])
    end
end

team_manager/app/helpers/events_helper.rb
module EventsHelper
end

team_manager/app/helpers/images_helper.rb
module ImagesHelper
end

team_manager/app/helpers/reports_helper.rb
module ReportsHelper
end

team_manager/app/helpers/tasks_helper.rb
module TasksHelper
end

team_manager/app/helpers/usages_helper.rb
module UsagesHelper
end

team_manager/app/helpers/users_helper.rb
module UsersHelper
end

team_manager/app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error explanation">
      <p><%= pluralize(@task.errors.count, "error") %> 入力内容が適切ではありません。<p>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :due %><br>
    <%= f.datetime_select :due %>
  </p>
   
  <p>
    <%= f.label "タスク責任者" %>
    <%= f.fields_for :tasks_users, @task.tasks_users do |tu| %><br>
      <%= tu.collection_select :user_id, User.all, :id, :name %>
	<% end %>
  </p>
  
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit class: "btn btn-primary"%>
  </p>
<% end %>

team_manager/app/views/tasks/_report.html.erb
<h5>【タスク一覧】</h5>
  <table class="table">
    <tr>
	  <th>タスク</th>
    </tr>
    <% @project.tasks.each do |task| %>
    <tr>
	  <td><%= task.title %></td>
    </tr>
    <% end %>
  </table>

team_manager/app/views/tasks/_tasks.html.erb
<h5>【最新タスク】</h5>
<%= link_to "タスクの追加", new_project_task_path(@project) %> | 
<%= link_to "タスク一覧", project_tasks_path(@project) %>
  <table class="table">
    <tr>
	  <th>Title</th>
	  <th>Description</th>
	  <th>Due</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
	  <td><%= link_to task.title, project_task_path(@project, task) %></td>
	  <td><%= task.due.to_s(:db) %></td>
	  <td><%= task.content %></td>
    </tr>
    <% end %>
  </table>

team_manager/app/views/tasks/_users.html.erb
<h5>関連ユーザー</h5>
<%= link_to "メンバー変更", task_users_edit_path(@task.project_id, @task) %><br>
<table class="table">
  <tr>
	<th>Name</th>
	<th>Generation</th>
	<th>Email</th>
  </tr>
  <% @task.users.each do |user| %>
  <tr>
	<td><%= user.name %></td>
	<td><%= user.generation %></td>
	<td><%= user.email %></td>
  </tr>
  <% end %>
</table>

team_manager/app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>
<%= render 'form' %>
<%= link_to 'プロジェクトページに戻る', project_path(@project) %>

team_manager/app/views/tasks/index.html.erb
<h1><%= @project.title %></h1>
<h3>タスク一覧</h3>
<%= link_to 'タスクの追加', new_project_task_path(@project) %> 
<table class="table table-default">
  <tr>
    <th>Title</th>
	<th>Due</th>
	<th>Content</th>
  </tr> 
  <% @tasks.each do |task| %>
    <tr>
	  <td><%= link_to task.title, project_task_path(@project, task) %> </td> 
      <td><%= task.due.to_s(:db) %></td>
      <td><%= task.content %></td>
	  <td><%= link_to '編集', edit_project_task_path(@project, task) %></td>
      <td><%= link_to '削除', project_task_path(@project, task),
              method: :delete, data: { confirm: '本当によろしいですか？' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'プロジェクト一覧に戻る', projects_path %>
 | <%= link_to 'プロジェクトページに戻る', project_path(@project) %>

team_manager/app/views/tasks/new.html.erb
<h1>新規レポートの作成</h1>
<%= render 'form' %>
<%= link_to 'プロジェクトページに戻る', project_path(params[:project_id]) %>

team_manager/app/views/tasks/show.html.erb
<h2><%= @project.title %></h2>
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>
 
<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>
<%= render 'users' %>
<%= link_to 'プロジェクトページに戻る', project_path(@project) %>
| <%= link_to 'タスク内容を編集する', edit_project_task_path(@project, @task) %>

team_manager/app/views/tasks/users_edit.html.erb
<h1>メンバーの編集</h1>
<table class="table">
  <tr>
    <th>名前</th>
    <th></th>
  </tr>
  <% @task.users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
	<td><%= link_to '削除', project_task_path(@task.project_id, @task)+"/users_edit/"+user.id.to_s, method: :delete,
	        data: { confirm: '本当によろしいですか？' }%></td>
  </tr>
  <% end %>
</table>

<h4>メンバーの追加</h4>
<p>
<%= form_for([@project, @task]) do |f| %>
  <%= f.fields_for :tasks_users, @new_user do |tu| %>
    <%= tu.collection_select :user_id, User.all, :id, :name %>
  <% end %>
</p>
<p>
  <%= f.submit("追加する") %>
</p>
<% end %>

<%= link_to "タスクページに戻る", project_task_path(@project, @task) %>