team_manager/config/routes.rb
TeamManager::Application.routes.draw do
  root "dashbords#home"
  
  devise_for :users
  resources :projects do
    resources :reports
	resources :tasks
  end
  resources :users
  resources :materials
  resources :accountings do
    resources :images
  end
  resources :accountings
  
  get "static_pages/contact"
  get "static_pages/usage"
  
  get "projects/:id/members_edit", to:"projects#members_edit", as: "project_members_edit"
  post "projects/:id/members_edit", to:"projects#members_edit"
  delete "projects/:id/members_edit/:user_id", to:"projects#member_delete"
  
  get "materials/:id/users_edit", to:"materials#users_edit", as: "material_users_edit"
  post "materials/:id/users_edit", to:"materials#users_edit"
  delete "materials/:id/users_edit/:user_id", to:"materials#user_delete"
  
  get "projects/:project_id/reports/:id//users_edit", to:"reports#users_edit", as: "report_users_edit"
  post "projects/:project_id/reports/:id/users_edit", to:"reports#users_edit"
  delete "projects/:project_id/reports/:id/users_edit/:user_id", to:"reports#user_delete"
  
  get "projects/:project_id/tasks/:id//users_edit", to:"tasks#users_edit", as: "task_users_edit"
  post "projects/:project_id/tasks/:id/users_edit", to:"tasks#users_edit"
  delete "projects/:project_id/tasks/:id/users_edit/:user_id", to:"tasks#user_delete"
  
  get 'accountings/:id/edit_status' => 'accountings#edit_status', as: :edit_status

end

team_manager/app/models/accounting.rb
class Accounting < ActiveRecord::Base
  belongs_to :user
  has_many :images, as: :imageable, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :images
  
  validates :title, presence: true
  validates :purpose, presence: true
  validates :application_date, presence: true  
  validates :status, presence:true
end

team_manager/app/models/event.rb
class Event < ActiveRecord::Base
end

team_manager/app/models/event2.rb
class Event2 < ActiveRecord::Base
end

team_manager/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :image_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image_file, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/models/material.rb
class Material < ActiveRecord::Base
	has_many :materials_users, dependent: :destroy
    has_many :users, through: :materials_users
	accepts_nested_attributes_for :materials_users

    validates :title, presence:true
	validates :filename, presence:true
	validates :filetype, presence:true
end

team_manager/app/models/material_user.rb
class MaterialUser < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

team_manager/app/models/materials_user.rb
class MaterialsUser < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

team_manager/app/models/project.rb
class Project < ActiveRecord::Base
    has_many :reports, dependent: :destroy
	has_many :tasks, dependent: :destroy

	has_many :projects_users, dependent: :destroy
	has_many :users, through: :projects_users
	accepts_nested_attributes_for :projects_users

    validates :title, presence: true
	validates :description, presence: true
	#validates :project_manager_id, presence: true

end

team_manager/app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

team_manager/app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :project
  
  has_many :reports_users
  has_many :users, through: :reports_users
  accepts_nested_attributes_for :reports_users

  validates :title, presence: true
  validates :text, presence: true
end

team_manager/app/models/report_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :report
  belongs_to :user
end

team_manager/app/models/reports_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :report
end

team_manager/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

team_manager/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  
  has_many :tasks_users
  has_many :users, through: :tasks_users
  accepts_nested_attributes_for :tasks_users

  validates :title, presence: true
  validates :due, presence: true
  validates :content, presence: true
end

team_manager/app/models/tasks_user.rb
class TasksUser < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

team_manager/app/models/user.rb
class User < ActiveRecord::Base
  has_many :materials_users
  has_many :materials, through: :materials_users

  has_many :tasks_users
  has_many :tasks, through: :tasks_users
  
  has_many :reports_users
  has_many :reports, through: :reports_users

  has_many :projects_users, dependent: :destroy
  has_many :projects, through: :projects_users

  has_many :accountings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :description, presence: true
  validates :generation, presence: true
  validates :name, presence: true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "60x60>" }, :default_url => "defaults/avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_project, only: [:new, :create, :show, :edit, :update, :destroy, :index, :users_edit, :user_delete]
  before_action :set_report, only: [:show, :edit, :update, :destroy, :users_edit, :user_delete]

  def new
    @report = @project.reports.build
	@report.reports_users.build
  end

  def create
    @report = @project.reports.create(report_params)
	if @report.save
	  redirect_to project_report_path(@project, @report)
	else
	  render 'new'
	end
  end

  def index
    @reports = @project.reports.all
  end

  def show
  end

  def edit
  end

  def update
    if @report.update(report_params)
	  redirect_to project_report_path(@project, @report)
    else
      render 'edit'
    end
  end
 
  def destroy
    @report.destroy
    redirect_to project_path(@project)
  end

  def users_edit
    @new_user = @report.reports_users.build
	render 'users_edit'
  end
   
  def user_delete
    @report_user = @report.reports_users.where(user_id: params[:user_id], report_id: @report.id).first
    @report_user.destroy
    redirect_to report_users_edit_path(@report.project_id, @report)
  end

  private
    def report_params
      params.require(:report).permit(:id, :title, :user_id, :text, users_attributes: [:id, :name], reports_users_attributes: [:id, :user_id, :report_id])
    end
  
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_report
      @report = Report.find(params[:id])
    end
end

team_manager/app/helpers/events_helper.rb
module EventsHelper
end

team_manager/app/helpers/images_helper.rb
module ImagesHelper
end

team_manager/app/helpers/reports_helper.rb
module ReportsHelper
end

team_manager/app/helpers/tasks_helper.rb
module TasksHelper
end

team_manager/app/helpers/usages_helper.rb
module UsagesHelper
end

team_manager/app/helpers/users_helper.rb
module UsersHelper
end

team_manager/app/views/reports/_form.html.erb
<%= form_for([@project, @report]) do |f| %>
  <% if @report.errors.any? %>
	<div id="error explanation">
	  <p><%= pluralize(@report.errors.count, "error") %> 入力内容が適切ではあ>    りません。<p>
	  <ul>
	  <% @project.errors.full_messages.each do |msg| %>
	    <li> <%= msg %></li>
      <% end %>
	  </ul>
	</div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
  記録者
    <%= f.fields_for :reports_users, @report.reports_users do |ru| %><br>
      <%= ru.collection_select :user_id, @project.users.all, :id, :name %>
    <% end %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit class: "btn btn-primary"%>
  </p>
<% end %>

team_manager/app/views/reports/_reports.html.erb
<h5>【最新レポート】</h5> 
<%= link_to "レポートの追加", new_project_report_path(@project) %> | 
<%= link_to "レポート一覧", project_reports_path(@project) %>
  <table class="table">
    <tr>
	  <th>Title</th>
	  <th>Description</th>
	  <th>Author</th>
    </tr>
    <% @reports.each do |report| %>
    <tr>
	  <td><%= link_to report.title, project_report_path(@project, report) %></td>
	  <td><%= report.text %></td>
	  <td>
	  <% report.users.all.each do |u| %>
	    <%= u.name %>
      <% end %>
	  </td>
    </tr>
    <% end %>
  </table>

team_manager/app/views/reports/_users.html.erb
<h5>関連ユーザー</h5>
<%= link_to "メンバー変更", report_users_edit_path(@report.project_id, @report) %><br>
<table class="table">
  <tr>
	<th>Name</th>
	<th>Generation</th>
	<th>Email</th>
  </tr>
  <% @report.users.each do |user| %>
  <tr>
	<td><%= user.name %></td>
	<td><%= user.generation %></td>
	<td><%= user.email %></td>
  </tr>
  <% end %>
</table>

team_manager/app/views/reports/edit.html.erb
<h1>レポートの編集</h1>
<%= render 'form' %>
<%= link_to 'プロジェクトページに戻る', project_path(@project) %>

team_manager/app/views/reports/index.html.erb
<h1><%= @project.title %></h1>
<h3>レポート一覧</h3>
<%= link_to 'レポートの追加', new_project_report_path(@project) %> 
<table class="table table-default">
  <tr>
    <th>Title</th>
	<th>Text</th>
	<th>Author</th>
	<th colspan="3"></th>
  </tr> 
  <% @reports.each do |report| %>
    <tr>
	  <td><%= link_to report.title, project_report_path(@project, report) %> </td> 
      <td><%= report.text %></td>
      <td>
	  <% report.users.all.each do |u| %>
	    <%= u.name %>
	  <% end %>
	  </td>
	  <td><%= link_to '編集', edit_project_report_path(@project, report) %></td>
      <td><%= link_to '削除', project_report_path(@project, report),
	          method: :delete, data: { confirm: '本当によろしいですか？' } %>    </td>
    </tr>
  <% end %>
</table>
<%= link_to 'プロジェクト一覧に戻る', projects_path %>
 | <%= link_to 'プロジェクトページに戻る', project_path(@project) %>

team_manager/app/views/reports/new.html.erb
<h1>新規レポートの作成</h1>
<%= render 'form' %>
<%= link_to 'プロジェクトページに戻る', project_path(params[:project_id]) %>

team_manager/app/views/reports/show.html.erb
<h2><%= @project.title %></h2>
<p>
  <strong>Title:</strong>
  <%= @report.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @report.text %>
</p>

<%= render 'users' %>
<%= link_to 'レポート一覧に戻る', project_reports_path %>
| <%= link_to 'レポート内容を編集する', edit_project_report_path(@project, @report) %>

team_manager/app/views/reports/users_edit.html.erb
<h1>メンバーの編集</h1>
<table class="table">
  <tr>
    <th>名前</th>
    <th></th>
  </tr>
  <% @report.users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
	<td><%= link_to '削除', project_report_path(@report.project_id, @report)+"/users_edit/"+user.id.to_s, method: :delete,
	        data: { confirm: '本当によろしいですか？' }%></td>
  </tr>
  <% end %>
</table>

<h4>メンバーの追加</h4>
<p>
<%= form_for([@project, @report]) do |f| %>
  <%= f.fields_for :reports_users, @new_user do |ru| %>
    <%= ru.collection_select :user_id, User.all, :id, :name %>
  <% end %>
</p>
<p>
  <%= f.submit("追加する") %>
</p>
<% end %>

<%= link_to "レポートページに戻る", project_report_path(@project, @report) %>