team_manager/config/routes.rb
TeamManager::Application.routes.draw do
  root "dashbords#home"
  
  devise_for :users
  resources :projects do
    resources :reports
	resources :tasks
  end
  resources :users
  resources :materials
  resources :accountings do
    resources :images
  end
  resources :accountings
  
  get "static_pages/contact"
  get "static_pages/usage"
  
  get "projects/:id/members_edit", to:"projects#members_edit", as: "project_members_edit"
  post "projects/:id/members_edit", to:"projects#members_edit"
  delete "projects/:id/members_edit/:user_id", to:"projects#member_delete"
  
  get "materials/:id/users_edit", to:"materials#users_edit", as: "material_users_edit"
  post "materials/:id/users_edit", to:"materials#users_edit"
  delete "materials/:id/users_edit/:user_id", to:"materials#user_delete"
  
  get "projects/:project_id/reports/:id//users_edit", to:"reports#users_edit", as: "report_users_edit"
  post "projects/:project_id/reports/:id/users_edit", to:"reports#users_edit"
  delete "projects/:project_id/reports/:id/users_edit/:user_id", to:"reports#user_delete"
  
  get "projects/:project_id/tasks/:id//users_edit", to:"tasks#users_edit", as: "task_users_edit"
  post "projects/:project_id/tasks/:id/users_edit", to:"tasks#users_edit"
  delete "projects/:project_id/tasks/:id/users_edit/:user_id", to:"tasks#user_delete"
  
  get 'accountings/:id/edit_status' => 'accountings#edit_status', as: :edit_status

end

team_manager/app/models/accounting.rb
class Accounting < ActiveRecord::Base
  belongs_to :user
  has_many :images, as: :imageable, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :images
  
  validates :title, presence: true
  validates :purpose, presence: true
  validates :application_date, presence: true  
  validates :status, presence:true
end

team_manager/app/models/event.rb
class Event < ActiveRecord::Base
end

team_manager/app/models/event2.rb
class Event2 < ActiveRecord::Base
end

team_manager/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :image_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image_file, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/models/material.rb
class Material < ActiveRecord::Base
	has_many :materials_users, dependent: :destroy
    has_many :users, through: :materials_users
	accepts_nested_attributes_for :materials_users

    validates :title, presence:true
	validates :filename, presence:true
	validates :filetype, presence:true
end

team_manager/app/models/material_user.rb
class MaterialUser < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

team_manager/app/models/project.rb
class Project < ActiveRecord::Base
    has_many :reports, dependent: :destroy
	has_many :tasks, dependent: :destroy

	has_many :projects_users, dependent: :destroy
	has_many :users, through: :projects_users
	accepts_nested_attributes_for :projects_users

    validates :title, presence: true
	validates :description, presence: true
	#validates :project_manager_id, presence: true

end

team_manager/app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

team_manager/app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :project
  
  has_many :reports_users
  has_many :users, through: :reports_users
  accepts_nested_attributes_for :reports_users

  validates :title, presence: true
  validates :text, presence: true
end

team_manager/app/models/report_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :report
  belongs_to :user
end

team_manager/app/models/reports_user.rb
class ReportsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :report
end

team_manager/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

team_manager/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  
  has_many :tasks_users
  has_many :users, through: :tasks_users
  accepts_nested_attributes_for :tasks_users

  validates :title, presence: true
  validates :due, presence: true
  validates :content, presence: true
end

team_manager/app/models/tasks_user.rb
class TasksUser < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

team_manager/app/models/user.rb
class User < ActiveRecord::Base
  has_many :materials_users
  has_many :materials, through: :materials_users

  has_many :tasks_users
  has_many :tasks, through: :tasks_users
  
  has_many :reports_users
  has_many :reports, through: :reports_users

  has_many :projects_users, dependent: :destroy
  has_many :projects, through: :projects_users

  has_many :accountings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :description, presence: true
  validates :generation, presence: true
  validates :name, presence: true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "60x60>" }, :default_url => "defaults/avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

team_manager/app/helpers/events_helper.rb
module EventsHelper
end

team_manager/app/helpers/images_helper.rb
module ImagesHelper
end

team_manager/app/helpers/tasks_helper.rb
module TasksHelper
end

team_manager/app/helpers/usages_helper.rb
module UsagesHelper
end

team_manager/app/helpers/users_helper.rb
module UsersHelper
end

team_manager/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Team Manager", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">プロジェクト<b class="caret"></b></a>
		  <span class="dropdown-arrow"></span>
          <ul class="dropdown-menu">
            <li><%= link_to 'プロジェクト一覧', projects_path %></li>
            <li><a href="#">過去のプロジェクト</a></li>
          </ul>
        </li>
		
		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">資料<b class="caret"></b></a>
          <span class="dropdown-arrow"></span>
		  <ul class="dropdown-menu">
            <li><%= link_to '資料一覧', materials_path %></li>
            <li><a href="#">議事録</a></li>
            <li class="divider"></li>
            <li><a href="#">引き継ぎ資料</a></li>
          </ul>
        </li>
   <li class="dropdown">
      <a href='#' class="dropdown-toggle" data-toggle="dropdown">各種申請<b class="caret"></b></a>
      <span class="dropdown-arrow"></span>
	  <ul class="dropdown-menu">
        <li><%= link_to '経理申請一覧',accountings_path %></li>
      </ul>
   </li>

		<li><%= link_to 'メンバー', users_path %></li> 
	  </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>マイメニュー<b class="caret"></b></a>
          <span class="dropdown-arrow"></span>
		  <ul class="dropdown-menu">
	        <% if user_signed_in? %>
	          <li><a href="#"><%= current_user.email %></a></li>
	          <li><%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %></li> 
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link' %></li>
	        <% else %>
	          <li><%= link_to "Sign up", new_user_registration_path, class: 'navbar-link' %></li> 
	          <li><%= link_to "Login", new_user_session_path, class: 'navbar-link' %></li>
	        <% end %>
          </ul>
        </li>
      </ul>
	  <p class="navbar-text pull-right">
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

team_manager/app/views/layouts/_side_bar.html.erb
<div class="navbar-header">
 <!-- できればロゴの画像イメージが欲しい　-->
  <h3><%= link_to "Team Manager", dashbords_home_path, class: "navbar-brand" %></h3>
</div>

<ul class="nav navbar-inverse" role="navigation">
  <table style="width:100%;">
    <% if user_signed_in? %>
	  <tr><td><div class="text-center"><%= image_tag current_user.avatar.url(:thumb) %></div></td></tr>
	  <tr><td><%= current_user.name %></td></tr>
      <tr><td><%= current_user.email %></td></tr>
      <tr><td><div class="text-center"><%= link_to 'Edit profile', edit_user_registration_path %></div></td></tr>
      <tr><td><div class="text-center"><%= link_to "Logout", destroy_user_session_path, method: :delete %></div></td></tr>
    <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li> 
      <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
 </table>
  
  <li class="dropdown">
    <a href="#" class="dropdown-inverse" data-toggle="dropdown">プロジェクト<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'プロジェクト一覧', projects_path %></li>
      <li><a href="#">過去のプロジェクト</a></li>
    </ul>
  </li>
		
  <li class="dropdown">
    <a href="#" class="dropdown-inverse">資料<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to '資料一覧', materials_path %></li>
      <li><a href="#">議事録</a></li>
      <li class="divider"></li>
      <li><a href="#">引き継ぎ資料</a></li>
    </ul>
  </li>
  
  <li class="dropdown">
    <a href='#' class="dropdown-inverse" data-toggle="dropdown">各種申請<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to '経理申請一覧',accountings_path %></li>
    </ul>
  </li>

  <li><%= link_to 'メンバー', users_path %></li>
</ul>

team_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamManager</title>
  <%= include_gon(init: true) %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/header' %>
  <div id="main" class="container" style="padding-top: 100px;">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>